"""Shared PCM and playback contracts for local, browser and Zoom transports."""
from dataclasses import dataclass
from typing import AsyncIterator, Protocol


@dataclass(frozen=True)
class AudioFrame:
    sequence: int
    pcm: bytes  # Signed 16-bit little-endian, mono, headerless.
    sample_rate: int = 32000
    gated: bool | None = None  # Capture-time silence decision, when supplied by transport.
    speaker_id: str | None = None
    timestamp_ms: int | None = None  # Frame start on the meeting capture clock.


class AudioMeeting(Protocol):
    async def join(self) -> None: ...
    def audio(self) -> AsyncIterator[AudioFrame]: ...
    async def play_audio(self, pcm: bytes, sample_rate: int) -> None: ...
    async def stop_speaking(self) -> None: ...
    async def leave(self) -> None: ...

# Realtime transport is separate from the existing 32 kHz, whole-reply AudioMeeting.
class CancellationFlag(Protocol):
    def is_set(self) -> bool: ...


class StreamingPlayback(Protocol):
    item_id: str
    generated: int
    finished: bool
    cancelled: CancellationFlag

    def played_ms(self, now: float | None = None) -> int: ...


class RealtimeAudioTransport(Protocol):
    """PCM16 mono 24 kHz in/out. append_output must enqueue, never await playback.

    outputs retains item playback records for truncation when a user interrupts.
    Each record exposes cancelled.is_set(), generated byte count, and played_ms().
    Transport implementations must bound queues and report capture/playback loss.
    stop_speaking cancels ALL outputs and discards pending PCM, not just the current
    item. On return replacement output must be safe (Zoom uses cancel-v1). Progress
    is only a truncation estimate; it never confirms semantic delivery to a human.
    """
    outputs: dict[str, StreamingPlayback]
    output: StreamingPlayback | None

    async def join(self) -> None: ...
    def audio(self) -> AsyncIterator[AudioFrame]: ...
    def append_output(self, item_id: str, pcm: bytes) -> None: ...
    def finish_output(self, item_id: str) -> None: ...
    async def stop_speaking(self) -> None: ...
    async def leave(self) -> None: ...
