/* Detailed presentation narrative. Dialogue and artifact sketches are illustrative unless explicitly stated. */
window.SPARKIE_STORY = {
  counts: [1, 1, 4, 6, 1, 4, 3, 4, 3, 1],
  market: [
    {name:'Granola', url:'https://www.granola.ai/', icon:'assets/market/granola-icon.ico', image:'assets/market/granola-website.jpg', fallback:'assets/market/granola-product.png', strength:'Meeting memory. No bot to admit.', tradeoff:'The notepad does not occupy a speaking seat.', focus:'What if the assistant could take the floor?', label:'Meeting intelligence'},
    {name:'Vapi', url:'https://vapi.ai/', icon:'assets/market/vapi-icon.ico', image:'assets/market/vapi-website.jpg', fallback:'assets/market/vapi-product.png', strength:'Voice conversations connected to tools.', tradeoff:'You still build the meeting and context layer.', focus:'What if it already understood the room?', label:'Voice infrastructure'},
    {name:'ZoomMate', url:'https://www.zoom.com/en/products/ai-assistant/', icon:'assets/market/zoom-icon.ico', image:'assets/market/zoom-website.jpg', fallback:'assets/market/zoom-product.jpg', strength:'Native context. Documents and workflows.', tradeoff:'Its packaged experience follows Zoom’s surfaces and connectors.', focus:'What if the workbench were your own project?', label:'Workplace execution'},
    {name:'Sparkie', url:'https://github.com/Hope7Happiness/sparkie', icon:'assets/sparkie-icon.png', image:'assets/scenes/collaboration.jpg', fallback:'assets/scenes/collaboration.jpg', strength:'Spoken delegation. Direct project work. Iteration in the room.', tradeoff:'A macOS Zoom prototype, with setup and human review.', focus:'A participant with hands on the project.', label:'Our focus'}
  ],
  inspiration: [
    {title:'A product fork.',scene:'The launch is close. The team has two ways to onboard new users.',image:'assets/scenes/planning.jpg',roles:['Product lead','Engineer','Product lead → Sparkie'],lines:['“A guided setup could help people finish the first project.”','“But a checklist is cheaper to ship. We need to compare the tradeoffs.”','“Sparkie, turn those two options into a brief, including effort and risks.”'],result:'The discussion becomes a decision brief.'},
    {title:'A customer call.',scene:'The customer has changed the priority in the middle of the call.',image:'assets/scenes/meeting.jpg',roles:['Customer','Account lead','Account lead → Sparkie'],lines:['“The dashboard can wait. We need a reliable export every Friday.”','“Understood. Let’s make reporting the first milestone.”','“Sparkie, draft a follow-up around that priority. Leave dates for us to confirm.”'],result:'A tailored draft, ready for human review.'}
  ],
  rhythm: [
    {title:'Delegate a piece of the work.',detail:'“Sparkie, write an outline from that discussion.”',voice:'Acknowledge',worker:'Context snapshot'},
    {title:'The conversation keeps moving.',detail:'The team discusses filming while the worker creates the file.',voice:'Available',worker:'Tools + project files'},
    {title:'Human speech gets the floor.',detail:'A confirmed interruption stops the voice; the task can keep running.',voice:'Yield to the room',worker:'Still working'},
    {title:'Return with something to inspect.',detail:'The result is queued for a quiet moment, then spoken back.',voice:'Report the result',worker:'Saved artifact'}
  ],
  conversation: [
    {title:'Follow the discussion.',role:'Teammate',line:'“Sparkie could help with the comparison later.”',response:'Keep listening.',detail:'A mention is context, not automatically a request.'},
    {title:'Wait for the complete request.',role:'Teammate → Sparkie',line:'“Sparkie, compare the options … including the setup costs.”',response:'Now respond.',detail:'Words + semantic completion → one full turn.'},
    {title:'Take the correction.',role:'Teammate → Sparkie',line:'“Wait—just the setup costs. Keep it short.”',response:'Yield, then follow the new request.',detail:'Fast speech confirmation gives the floor back.'}
  ],
  architecture: [
    {title:'Separate people before interpretation.',detail:'Zoom human tracks feed words and semantic completion in parallel.'},
    {title:'Route a complete thought.',detail:'Align the final words. Gemini decides whether Sparkie was addressed.'},
    {title:'Speak, with human priority.',detail:'Realtime voices the answer. Confirmed human speech takes priority over playback.'},
    {title:'Delegate, execute, report.',detail:'A transcript snapshot reaches Devin; task results return to the voice.'}
  ],
  cases: [
    {name:'Demo film',status:'Documented Zoom workflow',image:'assets/scenes/collaboration.jpg',context:'Three teammates are planning Sparkie’s own demo film.',request:'“Write the outline. Then add the recording roles we agreed on.”',filename:'demo-outline.md',lines:['Opening scene','Live delegation','Open the saved result','+ Agreed recording roles'],review:'Open the file. Verify the follow-up edit.',artifactLabel:'Illustrative structure',evidence:'https://github.com/Hope7Happiness/sparkie#what-works-today'},
    {name:'Bug triage',status:'Worked scenario',image:'assets/scenes/planning.jpg',context:'Audio arrives, but the mixed queue grows while participant STT keeps running.',request:'“Trace the unused queue, propose a fix, and add a regression check.”',filename:'A patch + a focused regression test',lines:['Reproduce the failing path','Trace producer → consumer','Patch the routing boundary','Verify the original failure'],review:'Inspect the diff and the regression result.',artifactLabel:'Expected deliverable',evidence:'research.md#practical-worked-scenarios'},
    {name:'Customer follow-up',status:'Worked scenario',image:'assets/scenes/meeting.jpg',context:'Reporting became the priority; a delivery date was not agreed.',request:'“Draft the follow-up around exports. Keep the date explicitly open.”',filename:'customer-follow-up.md',lines:['Priority: reliable exports','Dashboard: later discussion','Delivery date: to confirm','Next step: review together'],review:'Check the facts. A human approves sending.',artifactLabel:'Illustrative draft',evidence:'research.md#practical-worked-scenarios'}
  ]
};
Object.assign(window.SPARKIE_DECK, {slides:[
  {title:'Meet your fourth teammate.',chapter:'THE INVITATION',seconds:20,notes:'Picture a teammate who joins the Zoom call and understands the discussion already in progress. Sparkie can answer aloud, take on a task in your project, and return with a result. Our question is simple: can the work start before everyone leaves the meeting?',cue:'Open on the photograph. It illustrates collaboration, not a real Sparkie session.'},
  {title:'Can someone take this forward?',chapter:'THE HANDOFF',seconds:20,notes:'The team has chosen a direction. Someone now has to reconstruct the discussion, compare the options, and make the actual file. That handoff is the moment we are trying to shorten: the intention is already shared, so why lose the context before the work begins?',cue:'Pause on the question; keep this short.'},
  {title:'The gap is in the handoff.',chapter:'PRODUCT TRADEOFFS',seconds:60,notes:'Granola is strong at meeting memory without a bot. That design does not give the notepad a speaking seat. Vapi connects voice to tools, but a builder still needs the meeting transport and shared-context application. ZoomMate is the closest comparison: it already combines context and execution, through Zoom’s product surfaces and connectors. Sparkie explores a different workbench: the project itself, reached through spoken delegation and refined in the room. The cost is real too: this is a macOS Zoom prototype with setup, broad tool access, and human review. These are design tradeoffs, not a claim that other products cannot act.',cue:'Four beats: Granola → Vapi → ZoomMate → Sparkie. Official product links and images are on the slide. Explain each strength before its tradeoff. Zoom comparison is a product-surface distinction, not an assertion that Zoom lacks agent execution.'},
  {title:'Imagine the room.',chapter:'INSPIRATION',seconds:45,notes:'Here is a product review. One person favors guided onboarding, another a simpler checklist. Now the instruction to Sparkie has meaning: compare those options using the discussion as context. Change the room to a customer call. The customer moves reporting ahead of the dashboard. The follow-up should reflect that shift, without inventing a deadline. These are illustrative conversations. The point is that a useful request grows out of the shared discussion, rather than starting as a blank chat prompt.',cue:'Six beats: three dialogue turns in each of two scenes. Read only the key line from each beat. Names identify roles, not real people. Use the next slide for real-session evidence.'},
  {title:'Watch the work happen.',chapter:'THE REAL DEMO',seconds:60,notes:'In the real demo, the team is planning the film you are watching. Sparkie receives the request to create the outline while the discussion continues. We open the real file, then ask it to incorporate the agreed recording roles. Listen for the acknowledgement, but look at the file for evidence of completion.',cue:'Use a real 60-second clip. Placeholder imagery is not evidence. Label shortened waits. A human opens and shares the file. If no recording is supplied, describe the planned demo slot honestly.'},
  {title:'Two rhythms. One teammate.',chapter:'THE EXECUTION LOOP',seconds:35,notes:'An acknowledgement belongs to the voice loop. Execution belongs to a separate worker. The worker starts with the finalized transcript available at delegation and works in the project while the room continues talking. If a person interrupts, the voice yields; this does not automatically cancel the task. A completed result returns through the task layer and can be reported at a quiet moment.',cue:'Four beats: delegate, work while talking, human interruption, result. The illuminated routes are a conceptual sequence, not measured timing. Task cancellation is an explicit operation.'},
  {title:'Read the room.',chapter:'CONVERSATIONAL JUDGMENT',seconds:25,notes:'The same assistant needs judgment about participation. Mentioning Sparkie in discussion is not always an invitation. A pause inside a request should not throw away the rest of the thought. And when a person corrects the request, the voice should yield. We handle these as different signals in the same conversation, rather than one mute switch.',cue:'Three beats: indirect mention, complete request with a pause, explicit correction. This is a scripted illustration, not a model benchmark. If asked: medium semantic VAD; a 350ms unconfirmed interruption candidate can resume buffered audio. Confirmed speech cancels the reply.'},
  {title:'Inside the loop.',chapter:'SYSTEM DESIGN',seconds:45,notes:'Separate human tracks enter from Zoom. Two parallel adapters supply the words and semantic turn completion. After those agree on a complete turn, Gemini checks whether it addresses Sparkie. Realtime handles the voice. Fast speech confirmation also has a priority path to stop playback. When a task is delegated, a transcript snapshot reaches the Devin worker with project tools. Its result returns through the task center to the voice. The bot’s own SDK track is excluded, although physical speaker echo can still reenter a human microphone.',cue:'Four builds: input split, complete-turn routing, voice and interruption path, asynchronous worker return. Current worker is SWE 1.6 Fast; Codex is selectable. The foreground consumes assembled text in this mode; separate Realtime sessions perform semantic audio completion.'},
  {title:'From request to review.',chapter:'PRACTICAL PLAYBOOKS',seconds:45,notes:'Here is what a useful handoff looks like at the artifact level. The documented Zoom demo creates an outline, then updates it with roles; the file must be opened and checked. For a concrete engineering walkthrough, an unused audio queue provides a failure to reproduce, a boundary to fix, and a regression to verify. For a customer follow-up, the useful output preserves priorities and explicitly leaves an unagreed date open. The latter two are worked scenarios. We are showing what to ask for and how to judge the result, not claiming every workflow has been run successfully in a meeting.',cue:'Three beats: demo film, bug triage, customer follow-up. Artifact panels are labelled illustrative or expected. Real-session evidence belongs in the recording slot. Keep the acceptance check visible.'},
  {title:'Leave with work in hand.',chapter:'THE CLOSE',seconds:15,notes:'Sparkie brings the conversation and the work into the same room. Address it, delegate a concrete task, and refine the result together. That is the experience we want to build: useful progress before the call ends.',cue:'End here. The visible links lead to the project homepage and repository, not backwards to another slide.'}
]});
